# Generated by Django 5.2.7 on 2025-11-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caldo_e_bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('preco', models.CharField(max_length=10)),
                ('classe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.CharField(max_length=10)),
                ('pedido', models.TextField()),
                ('visivel', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('total', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='petisco_e_pastel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('preco', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('classe', models.CharField(max_length=30)),
            ],
        ),
    ]
