# Generated by Django 5.2.7 on 2025-11-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_jhd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petisco_e_pastel',
            name='descricao',
        ),
    ]
